version: '3.4'

services:

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'

  galileodb:
    image: mariadb
    volumes:
      - ./galileodb:/var/lib/mysql
    env_file:
      - etc/galileo-db.env
    ports:
      - '3307:3306'


  galileo-api:
    image: galileo/galileo
    depends_on:
      - redis
      - galileodb
    command: "gunicorn -w 2 --preload -b 0.0.0.0:5001 -c galileo/webapp/gunicorn.conf.py 'galileo.webapp.wsgi:api' --log-level INFO"
    volumes:
      - ./apps-repo:/app/apps-repo
    env_file:
      - etc/galileo.env
      - etc/galileo-api.env
    ports:
      - '7701:5001'

  galileo-experimentd:
    image: galileo/galileo
    depends_on:
      - redis
      - galileodb
    command: "python -u -m galileo.cli.experimentd"
    env_file:
      - etc/galileo.env

  worker:
    image: galileo/galileo
    depends_on:
      - galileo-experimentd
    command: "python -u -m galileo.cli.worker"
    volumes:
      - type: bind
        source: ./worker
        target: /app/apps
    environment:
      - galileo_logging_level=INFO
      - galileo_redis_host=redis
      - galileo_apps_repository=http://galileo-api:5001
      - galileo_router_type=DebugRouter
      - galileo_trace_logging=sql
      - galileo_expdb_driver=mysql
      - galileo_expdb_mysql_host=galileodb
      - galileo_expdb_mysql_port=3306
      - galileo_expdb_mysql_db=galileo
      - galileo_expdb_mysql_user=galileo
      - galileo_expdb_mysql_password=galileo
