version: '3.4'

services:

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'

#  galileodb:
#    image: mariadb
#    volumes:
#      - ./galileodb:/var/lib/mysql
#    env_file:
#      - etc/galileo-db.env
#    ports:
#      - '3307:3306'

  galileo-api:
    image: galileo/galileo
    depends_on:
      - redis
    command: "gunicorn -w 2 --preload -b 0.0.0.0:5001 -c galileo/webapp/gunicorn.conf.py 'galileo.webapp.wsgi:api' --log-level DEBUG"
    volumes:
      - ./apps-repo:/app/apps-repo
      - ./data/galileodb:/data/galileodb
    env_file:
      - etc/galileo.env
      - etc/galileo-api.env
    ports:
      - '7701:5001'

  galileo-experimentd:
    image: galileo/galileo
    depends_on:
      - redis
    volumes:
      - ./data/galileodb:/data/galileodb
    command: "python -u -m galileo.cli.experimentd"
    env_file:
      - etc/galileo.env

  worker:
    image: galileo/galileo
    depends_on:
      - galileo-experimentd
    command: "python -u -m galileo.cli.worker"
    volumes:
      - type: bind
        source: ./worker
        target: /app/apps
      - ./data/galileodb:/data/galileodb
    environment:
      - galileo_logging_level=DEBUG
      - galileo_redis_host=redis
      - galileo_apps_repository=http://galileo-api:5001
      - galileo_router_type=DebugRouter
      - galileo_trace_logging=sql
      - galileo_expdb_driver=sqlite
      - galileo_expdb_sqlite_path=/data/galileodb/galileo.sqlite

