language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - coverage run --source=galileo -m pytest tests/

after_success:
  - coveralls
