# syntax=docker/dockerfile:experimental
#############
### build ###
#############
FROM python:3.7-alpine as base

FROM base as builder

# install galileo dependencies
RUN pip install 'redis==3.2.1'
RUN pip install 'pymq>=0.2.2'
RUN pip install 'symmetry-py-telemc>=0.2.0'
RUN pip install 'mysql-connector-python==8.0.16'

############
### prod ###
############
FROM base
COPY --from=builder /usr/local /usr/local

RUN mkdir /app
WORKDIR /app

COPY galileo galileo
